services:
  cartellino_notify:
    build: .
    container_name: cartellino_notify
    env_file:
      - .env
    # You might want to specify a command here, e.g., to run your main.py
    # command: python main.py job
