name: cartellino_notify
description: "Track your work hours and get notified when your shift ends"
publish_to: 'none'
version: 0.2.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_local_notifications: ^20.1.0
  google_fonts: ^8.0.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^1.1.1
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
