[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
service = "cartellino-notifier"
environment = "production"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "cartellino-notifier"

